### ISSUE TITLE
Assistance with Error in Running Command for LLaMA Model using VLLM

### ISSUE THREAD

**Issue by aligoldenhat** [usail-hkust/LLMTSCS#24]
Hi 
I am currently trying to run the following command:
```
!python run_open_LLM_with_vllm.py --llm_model llama \
                       --llm_path /content/llama \
                       --dataset hangzhou \
                       --traffic_file anon_4_4_hangzhou_real.json \
                       --proj_name TSCS
```
I have successfully installed `vllm` using the command `!pip install vllm`, and downloaded the `meta-llama/Llama-3.2-1B` model with the following code:

```
from transformers import AutoTokenizer, AutoModelForCausalLM
model_name = "meta-llama/Llama-3.2-1B"  
save_directory = "/content/llama"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)
tokenizer.save_pretrained(save_directory, safe_serialization=True)
model.save_pretrained(save_directory, safe_serialization=True)
```
However, when running the command, I encountered the following error:

`[rank0]: TypeError: Unexpected keyword argument 'min_length'`

To troubleshoot this, I removed the `min_length` argument from the `test_generation_kwargs` section:
```
        test_generation_kwargs = {
            #"min_length": -1,
            "top_k": 50,
            "top_p": 1.0,
            "temperature": 0.1,
            #"do_sample": True,
            "max_tokens": self.dic_agent_conf["NEW_MAX_TOKENS"],
            #"pad_token_id": self.tokenizer.pad_token_id,
            #"eos_token_id": self.tokenizer.eos_token_id
        }
```
 also commented out the `self.llm_model.eval()` line. Despite these changes, I am still encountering the following error:

```
end reset
  0% 0/120 [00:00<?, ?it/s]
Processed prompts:   0% 0/16 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
Processed prompts:   6% 1/16 [00:00<00:06,  2.21it/s, est. speed input: 1575.28 toks/s, output: 50.74 toks/s]
Processed prompts:  62% 10/16 [00:00<00:00, 22.76it/s, est. speed input: 12700.57 toks/s, output: 416.22 toks/s]
Processed prompts: 100% 16/16 [00:05<00:00,  2.84it/s, est. speed input: 2024.92 toks/s, output: 780.97 toks/s]
time: 0.0
Step time:  0.10885763168334961
Fail Num: 0 Queuing Vehicles: 0
  1% 1/120 [00:05<11:29,  5.80s/it]
Processed prompts:   0% 0/16 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
Processed prompts:   6% 1/16 [00:00<00:06,  2.46it/s, est. speed input: 1755.40 toks/s, output: 59.00 toks/s]
Processed prompts: 100% 16/16 [00:05<00:00,  2.94it/s, est. speed input: 2098.23 toks/s, output: 621.16 toks/s] 
  1% 1/120 [00:11<22:22, 11.28s/it]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/content/CityFlow/build/run_open_LLM_with_vllm.py", line 139, in <module>
[rank0]:     main(args)
[rank0]:   File "/content/CityFlow/build/run_open_LLM_with_vllm.py", line 134, in main
[rank0]:     trainer.train_test()
[rank0]:   File "/content/CityFlow/build/utils/llm_aft_trainer.py", line 1075, in train_test
[rank0]:     self.test(logger, 0)
[rank0]:   File "/content/CityFlow/build/utils/llm_aft_trainer.py", line 1006, in test
[rank0]:     dump_json(self.fail_logs, self.fail_log_file)
[rank0]:   File "/content/CityFlow/build/utils/my_utils.py", line 43, in dump_json
[rank0]:     raise e
[rank0]:   File "/content/CityFlow/build/utils/my_utils.py", line 40, in dump_json
[rank0]:     with open(file, 'w') as f:
[rank0]: FileNotFoundError: [Errno 2] No such file or directory: './fails/llama-anon_4_4_hangzhou_real.json-roadnet_4_4.json.json'
```

It seems there is an issue with saving or accessing the fail log file (`./fails/llama-anon_4_4_hangzhou_real.json-roadnet_4_4.json.json`), which is resulting in the error.

Could you kindly provide guidance on resolving this error? Any assistance or recommendations would be greatly appreciated.

**Comment by Gungnir2099** [comment]
Hello, I have updated the code and you will not encounter the last error anymore. Secondly, you may need to check the usage of `meta-llama/Llama-3.2-1B` to adjust the `test_generation_kwargs`.

**Comment by aligoldenhat** [comment]
Thanks for the update! Could you please confirm which LLM is being used for test_generation_kwargs?

**Comment by Gungnir2099** [comment]
You can use our pre-trained LightGPT or LLMs like Llama2, Llama3, and Qwen2. We have tested these models supporting our current configuration in code.

**Comment by ianboy302668** [comment]
你好，

我這幾天嘗試執行這個指令
```
python run_open_LLM_with_vllm.py --llm_model LightGPT-7B-Llama2 \
                                 --llm_path /home/msslab/IanChen/LLMLight/LightGPT-7B-Llama2 \
                                 --dataset hangzhou \
                                 --traffic_file anon_4_4_hangzhou_real.json \
                                 --proj_name TSCS_llmLight
```
我已安裝 `vllm == 0.6.2`，也從 [hugginface ](https://huggingface.co/collections/usail-hkust/llmlight-lightgpt-673ac5a619cbbe309165b56d)下載你們的預訓練模型 `LightGPT-7B-Llama2`
不過還是遇到上面提到的問題
`[rank0]: TypeError: Unexpected keyword argument 'min_length'

這邊我將`self.llm_model.eval()`印出的輸出貼上來: 
```
============= self.eng.reset() to be implemented ==========
INFO 02-12 15:34:33 llm_engine.py:226] Initializing an LLM engine (v0.6.1.dev238+ge2c6e0a82) with config: model='/home/msslab/IanChen/LLMLight/LightGPT-7B-Llama2', speculative_config=None, tokenizer='/home/msslab/IanChen/LLMLight/LightGPT-7B-Llama2', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=/home/msslab/IanChen/LLMLight/LightGPT-7B-Llama2, use_v2_block_manager=False, num_scheduler_steps=1, multi_step_stream_outputs=False, enable_prefix_caching=False, use_async_output_proc=True, use_cached_outputs=False, mm_processor_kwargs=None)
INFO 02-12 15:34:33 model_runner.py:1014] Starting to load model /home/msslab/IanChen/LLMLight/LightGPT-7B-Llama2...
Loading safetensors checkpoint shards:   0% Completed | 0/3 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  33% Completed | 1/3 [00:07<00:14,  7.40s/it]
Loading safetensors checkpoint shards:  67% Completed | 2/3 [00:09<00:04,  4.17s/it]
Loading safetensors checkpoint shards: 100% Completed | 3/3 [00:14<00:00,  4.82s/it]
Loading safetensors checkpoint shards: 100% Completed | 3/3 [00:14<00:00,  4.97s/it]

INFO 02-12 15:34:49 model_runner.py:1025] Loading model weights took 12.5523 GB
INFO 02-12 15:34:49 gpu_executor.py:122] # GPU blocks: 1055, # CPU blocks: 512
INFO 02-12 15:34:51 model_runner.py:1329] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 02-12 15:34:51 model_runner.py:1333] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 02-12 15:35:04 model_runner.py:1456] Graph capturing finished in 12 secs.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/msslab/IanChen/LLMTSCS_2/run_open_LLM_with_vllm.py", line 139, in <module>
[rank0]:     main(args)
[rank0]:   File "/home/msslab/IanChen/LLMTSCS_2/run_open_LLM_with_vllm.py", line 129, in main
[rank0]:     trainer = LLM_Inference_VLLM(dic_agent_conf_extra,
[rank0]:   File "/home/msslab/IanChen/LLMTSCS_2/utils/llm_aft_trainer.py", line 908, in __init__
[rank0]:     self.initialize()
[rank0]:   File "/home/msslab/IanChen/LLMTSCS_2/utils/llm_aft_trainer.py", line 953, in initialize
[rank0]:     self.initialize_llm()
[rank0]:   File "/home/msslab/IanChen/LLMTSCS_2/utils/llm_aft_trainer.py", line 939, in initialize_llm
[rank0]:     self.generation_kwargs = vllm.SamplingParams(**test_generation_kwargs)
[rank0]: TypeError: Unexpected keyword argument 'min_length'
[rank0]:[W212 15:35:04.717978353 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
```
您能為解決此錯誤提供指導嗎？任何幫助或建議將不勝感激。

**Comment by SQLai2099** [comment]
I have updated the code. Please try it again?

**Comment by ianboy302668** [comment]
Thanks for the update! 
Despite the update, I am still encountering the following errors: 
```
================ Start Test ================
 ============= self.eng.reset() to be implemented ==========
end reset
Traceback (most recent call last):
  File "/home/msslab/IanChen/LLMTSCS_2/run_open_LLM_with_vllm.py", line 143, in <module>
    main(args)
  File "/home/msslab/IanChen/LLMTSCS_2/run_open_LLM_with_vllm.py", line 134, in main
    trainer.train_test()
  File "/home/msslab/IanChen/LLMTSCS_2/utils/llm_aft_trainer.py", line 1077, in train_test
    self.test(logger, 0)
  File "/home/msslab/IanChen/LLMTSCS_2/utils/llm_aft_trainer.py", line 966, in test
    self.llm_model.eval()
AttributeError: 'LLM' object has no attribute 'eval'
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/msslab/IanChen/LLMTSCS_2/run_open_LLM_with_vllm.py", line 143, in <module>
[rank0]:     main(args)
[rank0]:   File "/home/msslab/IanChen/LLMTSCS_2/run_open_LLM_with_vllm.py", line 134, in main
[rank0]:     trainer.train_test()
[rank0]:   File "/home/msslab/IanChen/LLMTSCS_2/utils/llm_aft_trainer.py", line 1077, in train_test
[rank0]:     self.test(logger, 0)
[rank0]:   File "/home/msslab/IanChen/LLMTSCS_2/utils/llm_aft_trainer.py", line 966, in test
[rank0]:     self.llm_model.eval()
[rank0]: AttributeError: 'LLM' object has no attribute 'eval'
```
It is able to run after I comment `self.llm_model.eval()`, in line 966.
