### ISSUE TITLE
Mac电脑运行run_advanced_mplight.py报TypeError: cannot pickle 'cityflow.Engine' object，请问改如何解决？

### ISSUE THREAD

**Issue by nebulaeos** [usail-hkust/LLMTSCS#28]
Mac Book Pro（Apple M1 Pro芯片，MacOS：14.2.1）运行以下代码
```
python run_advanced_mplight.py --dataset hangzhou \
                               --traffic_file anon_4_4_hangzhou_real.json \
                               --proj_name TSCS
```
报错：TypeError: cannot pickle 'cityflow.Engine' object，CityFlow是check 代码后，pip install安装
异常链：
Step time:  0.13211798667907715
time: 3570.0, running_time: 0.14693808555603027
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 120/120 [00:16<00:00,  7.23it/s]
start logging.......................
before
Process Process-1:
Traceback (most recent call last):
  File "/Users/aisrch/miniconda3/envs/LLMTSCS/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/aisrch/miniconda3/envs/LLMTSCS/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/aisrch/workspace/pycharm/LLMTSCS/utils/utils.py", line 33, in pipeline_wrapper
    round_results = ppl.run(round=i, multi_process=False)
  File "/Users/aisrch/workspace/pycharm/LLMTSCS/utils/pipeline.py", line 155, in run
    generator_wrapper(cnt_round=cnt_round,
  File "/Users/aisrch/workspace/pycharm/LLMTSCS/utils/pipeline.py", line 76, in generator_wrapper
    generator.generate(logger)
  File "/Users/aisrch/workspace/pycharm/LLMTSCS/utils/generator.py", line 123, in generate
    self.env.bulk_log_multi_process()
  File "/Users/aisrch/workspace/pycharm/LLMTSCS/utils/cityflow_env.py", line 850, in bulk_log_multi_process
    p.start()
  File "/Users/aisrch/miniconda3/envs/LLMTSCS/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/aisrch/miniconda3/envs/LLMTSCS/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/aisrch/miniconda3/envs/LLMTSCS/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/aisrch/miniconda3/envs/LLMTSCS/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/aisrch/miniconda3/envs/LLMTSCS/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/aisrch/miniconda3/envs/LLMTSCS/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/aisrch/miniconda3/envs/LLMTSCS/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'cityflow.Engine' object

其中tensorflow-cpu=2.8.0为找到可用packeage，替换为了tensorflow-macos=2.8.0

请问是我环境哪里出了问题吗？会不会是因为tensorflow-macos这个包的缘故？

**Comment by SQLai2099** [comment]
我觉得这个和tensorflow关系不大，你可以尝试在Linux或者Windows上跑一下，看是否还有这个问题。

**Comment by nebulaeos** [comment]
> 我觉得这个和tensorflow关系不大，你可以尝试在Linux或者Windows上跑一下，看是否还有这个问题。

在ubuntu24.04上运行，是别的问题，我当时怀疑是硬件问题

**Comment by SQLai2099** [comment]
好的，现在解决了吗？

**Comment by nebulaeos** [comment]
还没有，我再换台电脑试试
